import PDFDocument from 'pdfkit';
import { AuditLog, AnnualClosing, Member, MonthlyLedger, Payment, PaymentAllocation, PolicyVersion, ShareHistory } from '../models/index.js';
import { IUser, UserRole } from '../types/models.js';
import { createError } from '../middlewares/error.js';

const money = (value: number) => `BDT ${Number(value || 0).toFixed(2)}`;
function pdf(title: string, lines: string[]): Promise<Buffer> { return new Promise((resolve, reject) => { const doc = new PDFDocument({ margin: 48, size: 'A4' }); const chunks: Buffer[] = []; doc.on('data', (chunk) => chunks.push(Buffer.from(chunk))); doc.on('end', () => resolve(Buffer.concat(chunks))); doc.on('error', reject); doc.fontSize(20).fillColor('#13213a').text('NS Foundation'); doc.fontSize(14).fillColor('#111827').text(title); doc.moveDown(); for (const line of lines) { doc.fontSize(9).fillColor('#374151').text(line, { width: 500 }); } doc.moveDown(); doc.fontSize(8).fillColor('#6b7280').text('Generated from authoritative NS Foundation records. Pending transferred-share entitlement is intentionally excluded.'); doc.end(); }); }
export class DocumentService {
  static async memberStatement(memberId: string, user: IUser) {
    if (![UserRole.ADMIN, UserRole.SUPER_ADMIN, UserRole.ACCOUNTANT].includes(user.role)) throw createError('Member statements are restricted to authorized staff.', 403);
    const member = await Member.findById(memberId).lean(); if (!member) throw createError('Member not found.', 404);
    const [shares, ledgers, payments, allocations] = await Promise.all([ShareHistory.find({ memberId }).sort({ effectiveMonth: 1 }).lean(), MonthlyLedger.find({ memberId }).sort({ month: 1 }).lean(), Payment.find({ memberId }).sort({ paymentDate: -1 }).lean(), PaymentAllocation.find({ memberId }).sort({ targetMonth: 1 }).lean()]);
    const paid = payments.reduce((sum, item) => sum + item.totalAmount, 0); const due = ledgers.reduce((sum, item) => sum + Math.max(0, item.principalDue + item.penaltyDue - item.principalPaid - item.penaltyPaid), 0); const advance = ledgers.reduce((sum, item) => sum + item.excessAdvance, 0);
    const lines = [`Member: ${member.memberId} - ${member.name}`, `Status: ${member.status} | Joined: ${member.joinDate.toISOString().slice(0, 10)}`, `Total paid: ${money(paid)} | Current due: ${money(due)} | Advance: ${money(advance)} | Cash-out due: ${money(member.cashoutDue || 0)}`, '', 'Share history:', ...shares.map((item) => `${item.effectiveMonth}: ${item.shareCount} share(s) (${item.eventType})`), '', 'Monthly obligations:', ...ledgers.map((item) => `${item.month}: due ${money(item.principalDue + item.penaltyDue)}, paid ${money(item.principalPaid + item.penaltyPaid)}, status ${item.status}`), '', 'Payments:', ...payments.map((item) => `${item.paymentDate.toISOString().slice(0, 10)} | ${item.receiptNumber} | ${money(item.totalAmount)} | ${item.paymentMethod}`), '', `Allocation records: ${allocations.length}`];
    return pdf('Member Statement', lines);
  }
  static async annualReport(year: number, user: IUser) { const closing = await AnnualClosing.findOne({ year, status: 'LOCKED' }).lean(); if (!closing && user.role !== UserRole.SUPER_ADMIN) throw createError('Annual reports are available only after the year is locked.', 403); const data = closing?.summary || {}; return pdf(`Annual Report ${year}${closing ? '' : ' - PROVISIONAL'}`, Object.entries(data).map(([key, value]) => `${key}: ${money(Number(value || 0))}`)); }
  static async auditPack(year: number, user: IUser) { if (user.role !== UserRole.SUPER_ADMIN) throw createError('Audit packs are restricted to Super Admin.', 403); const start = new Date(year, 0, 1); const end = new Date(year, 11, 31, 23, 59, 59); const [logs, versions] = await Promise.all([AuditLog.find({ createdAt: { $gte: start, $lte: end } }).sort({ createdAt: 1 }).limit(500).lean(), PolicyVersion.find({ createdAt: { $gte: start, $lte: end } }).sort({ createdAt: 1 }).lean()]); return pdf(`Audit Pack ${year}`, [`Audit events: ${logs.length}`, ...logs.map((item) => `${item.createdAt.toISOString()} | ${item.action} | ${item.entityName} | ${item.reason || ''}`), '', `Policy versions: ${versions.length}`, ...versions.map((item) => `Policy ${item.policyId} version ${item.versionNumber}: ${item.changeReason || ''}`)]); }
}
