import { Types } from 'mongoose';
import { AnnualClosing, AuditLog, CustodyAccount, CustodyMovement, Expense, InvestmentReturn, Member, MemberExitSettlement, MonthlyLedger, Payment, Policy, PolicyVersion } from '../models/index.js';
import { AnnualClosingStatus, IUser, MemberExitStatus, MovementSourceType, MovementType, MonthlyLedgerStatus, UserRole } from '../types/models.js';
import { createError } from '../middlewares/error.js';
import { CustodyService } from './custody.service.js';

const actor = (user: IUser) => (user as IUser & { _id: Types.ObjectId })._id;
const round = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;

export class GovernanceService {
  static async annualSummary(year: number) {
    const start = new Date(year, 0, 1); const end = new Date(year, 11, 31, 23, 59, 59, 999);
    const [payments, expenses, returns, ledgers, members] = await Promise.all([
      Payment.aggregate([{ $match: { paymentDate: { $gte: start, $lte: end }, status: { $ne: 'CANCELLED' } } }, { $group: { _id: null, collections: { $sum: '$totalAmount' }, principal: { $sum: '$principalAmount' }, penalties: { $sum: '$penaltyAmount' }, cashout: { $sum: '$cashoutCharge' } } }]),
      Expense.aggregate([{ $match: { date: { $gte: start, $lte: end } } }, { $group: { _id: null, expenses: { $sum: '$amount' } } }]),
      InvestmentReturn.aggregate([{ $match: { maturityDate: { $gte: start, $lte: end } } }, { $group: { _id: null, returns: { $sum: '$totalReturn' }, profit: { $sum: '$actualProfit' }, loss: { $sum: '$actualLoss' } } }]),
      MonthlyLedger.aggregate([{ $match: { month: { $gte: `${year}-01`, $lte: `${year}-12` } } }, { $group: { _id: null, dues: { $sum: { $subtract: ['$principalDue', '$principalPaid'] } }, advance: { $sum: '$excessAdvance' } } }]),
      Member.countDocuments(),
    ]);
    const custody = await CustodyService.getCustodySummary(); const payment = payments[0] || {}; const expense = expenses[0] || {}; const investmentReturn = returns[0] || {}; const ledger = ledgers[0] || {};
    return { year, members, collections: round(payment.collections || 0), principal: round(payment.principal || 0), penalties: round(payment.penalties || 0), cashoutCharges: round(payment.cashout || 0), expenses: round(expense.expenses || 0), investmentReturns: round(investmentReturn.returns || 0), realizedProfit: round(investmentReturn.profit || 0), realizedLoss: round(investmentReturn.loss || 0), outstandingDues: round(ledger.dues || 0), advances: round(ledger.advance || 0), custodyBalance: round(custody.totalLiquidFunds) };
  }
  static async createAnnualClosing(year: number, notes: string | undefined, user: IUser) { if (await AnnualClosing.exists({ year })) throw createError('An annual closing already exists for this year.', 409); const summary = await this.annualSummary(year); const closing = await AnnualClosing.create({ year, summary, preparedBy: actor(user), notes, status: AnnualClosingStatus.DRAFT }); await this.audit(user, 'CREATE_ANNUAL_CLOSING', 'AnnualClosing', closing._id, `Created annual closing draft for ${year}.`); return closing; }
  static async transitionAnnualClosing(id: string, action: 'review' | 'approve' | 'lock', user: IUser) { const closing = await AnnualClosing.findById(id); if (!closing) throw createError('Annual closing not found.', 404); const expected = action === 'review' ? AnnualClosingStatus.DRAFT : action === 'approve' ? AnnualClosingStatus.REVIEWED : AnnualClosingStatus.APPROVED; if (closing.status !== expected) throw createError(`Annual closing must be ${expected} before ${action}.`, 400); if ((action === 'approve' || action === 'lock') && user.role !== UserRole.SUPER_ADMIN) throw createError('Only Super Admin can approve or lock an annual closing.', 403); closing.status = action === 'review' ? AnnualClosingStatus.REVIEWED : action === 'approve' ? AnnualClosingStatus.APPROVED : AnnualClosingStatus.LOCKED; if (action === 'review') closing.reviewedBy = actor(user); if (action === 'approve') closing.approvedBy = actor(user); if (action === 'lock') closing.lockedBy = actor(user); await closing.save(); await this.audit(user, `ANNUAL_CLOSING_${action.toUpperCase()}`, 'AnnualClosing', closing._id, `${action} annual closing ${closing.year}.`); return closing; }
  static async listAnnualClosings() { return AnnualClosing.find().sort({ year: -1 }).populate('preparedBy reviewedBy approvedBy lockedBy', 'name email').lean(); }

  static async listPolicies() { return Policy.find().sort({ serialNumber: 1 }).lean(); }
  static async createPolicy(input: { serialNumber: number; title: string; category: string; content: string }, user: IUser) { const policy = await Policy.create({ ...input, createdBy: actor(user), updatedBy: actor(user), currentVersion: 1, isActive: true }); await PolicyVersion.create({ policyId: policy._id, versionNumber: 1, content: policy.content, changeReason: 'Initial version', modifiedBy: actor(user) }); await this.audit(user, 'CREATE_POLICY', 'Policy', policy._id, `Created policy ${policy.serialNumber}.`); return policy; }
  static async amendPolicy(id: string, input: { title?: string; category?: string; content: string; changeReason: string }, user: IUser) { if (!input.changeReason?.trim()) throw createError('A policy amendment reason is required.', 400); const policy = await Policy.findById(id); if (!policy) throw createError('Policy not found.', 404); policy.title = input.title || policy.title; policy.category = input.category || policy.category; policy.content = input.content; policy.currentVersion += 1; policy.updatedBy = actor(user); await policy.save(); await PolicyVersion.create({ policyId: policy._id, versionNumber: policy.currentVersion, content: input.content, changeReason: input.changeReason, modifiedBy: actor(user) }); await this.audit(user, 'AMEND_POLICY', 'Policy', policy._id, input.changeReason); return policy; }
  static async policyVersions(id: string) { return PolicyVersion.find({ policyId: id }).sort({ versionNumber: -1 }).populate('modifiedBy', 'name email').lean(); }

  static async proposeExit(memberId: string, eligibleAmount: number, notes: string | undefined, user: IUser) {
    const member = await Member.findById(memberId); if (!member) throw createError('Member not found.', 404); if (member.status !== 'ACTIVE') throw createError('Only active members can begin an exit settlement.', 400); if (Date.now() - member.joinDate.getTime() < 365 * 24 * 60 * 60 * 1000) throw createError('A member cannot leave within the first year of membership.', 400);
    const dues = await MonthlyLedger.exists({ memberId, status: { $in: [MonthlyLedgerStatus.DUE, MonthlyLedgerStatus.PARTIAL] } }); if (dues || (member.cashoutDue || 0) > 0) throw createError('Settle outstanding member dues and cash-out charges before exit.', 400); if (await MemberExitSettlement.exists({ memberId })) throw createError('An exit settlement already exists for this member.', 409);
    if (!Number.isFinite(eligibleAmount) || eligibleAmount < 0) throw createError('Eligible amount must be a non-negative number.', 400);
    const deductionRate = 9.99; const deductionAmount = round(eligibleAmount * deductionRate / 100); const netAmount = round(eligibleAmount - deductionAmount); const installmentAmount = round(netAmount / 4); const today = new Date(); const installments = Array.from({ length: 4 }, (_, index) => ({ dueDate: new Date(today.getFullYear(), today.getMonth() + index + 1, today.getDate()), amount: index === 3 ? round(netAmount - installmentAmount * 3) : installmentAmount, paidAmount: 0 }));
    const settlement = await MemberExitSettlement.create({ memberId: member._id, eligibleAmount, deductionRate, deductionAmount, netAmount, installmentAmount, installments, requestedBy: actor(user), notes, status: MemberExitStatus.PROPOSED }); await this.audit(user, 'PROPOSE_MEMBER_EXIT', 'MemberExitSettlement', settlement._id, `Proposed exit settlement for ${member.memberId}; eligible amount supplied for authorized review.`); return settlement;
  }
  static async approveExit(id: string, user: IUser) { if (user.role !== UserRole.SUPER_ADMIN) throw createError('Only Super Admin can approve an exit settlement.', 403); const settlement = await MemberExitSettlement.findById(id); if (!settlement) throw createError('Exit settlement not found.', 404); if (settlement.status !== MemberExitStatus.PROPOSED) throw createError('Only proposed settlements can be approved.', 400); settlement.status = MemberExitStatus.APPROVED; settlement.approvedBy = actor(user); await settlement.save(); await this.audit(user, 'APPROVE_MEMBER_EXIT', 'MemberExitSettlement', settlement._id, 'Approved member exit settlement.'); return settlement; }
  static async payExitInstallment(id: string, index: number, custodyAccountId: string, user: IUser) { if (user.role !== UserRole.SUPER_ADMIN) throw createError('Only Super Admin can release exit installments.', 403); const settlement = await MemberExitSettlement.findById(id); if (!settlement || ![MemberExitStatus.APPROVED, MemberExitStatus.PARTIALLY_PAID].includes(settlement.status)) throw createError('Approved exit settlement not found.', 404); const installment = settlement.installments[index]; if (!installment || installment.paidAmount > 0) throw createError('This installment is unavailable or already paid.', 400); const account = await CustodyAccount.findById(custodyAccountId); if (!account?.isActive) throw createError('An active custody account is required.', 400); const balance = await CustodyService.getDerivedAccountBalance(account._id); if (balance.currentBalance < installment.amount) throw createError('Insufficient custody balance for this installment.', 400); const movement = await CustodyMovement.create({ custodyAccountId: account._id, movementType: MovementType.OUT, amount: installment.amount, sourceType: MovementSourceType.FINAL_DISTRIBUTION, sourceRefId: settlement._id, date: new Date(), description: `Member exit installment ${index + 1}/4`, performedBy: actor(user) }); installment.paidAmount = installment.amount; installment.paidAt = new Date(); installment.custodyMovementId = movement._id; const done = settlement.installments.every((item) => item.paidAmount >= item.amount); settlement.status = done ? MemberExitStatus.SETTLED : MemberExitStatus.PARTIALLY_PAID; await settlement.save(); if (done) await Member.findByIdAndUpdate(settlement.memberId, { status: 'DROPPED' }); await this.audit(user, 'PAY_MEMBER_EXIT_INSTALLMENT', 'MemberExitSettlement', settlement._id, `Paid installment ${index + 1}/4.`); return settlement; }
  static async listExits() { return MemberExitSettlement.find().populate('memberId', 'memberId name').sort({ createdAt: -1 }).lean(); }
  private static async audit(user: IUser, action: string, entityName: string, entityId: Types.ObjectId, reason: string) { await AuditLog.create({ performedBy: actor(user), action, entityName, entityId, reason }); }
}
