import { NextFunction, Response } from 'express';
import { AuthRequest } from '../middlewares/auth.js';
import { createError } from '../middlewares/error.js';
import { GovernanceService } from '../services/governance.service.js';
export class GovernanceController {
  static async annualSummary(req: AuthRequest, res: Response, next: NextFunction) { try { res.json({ success: true, data: await GovernanceService.annualSummary(Number(req.params.year)) }); } catch (error) { next(error); } }
  static async createAnnual(req: AuthRequest, res: Response, next: NextFunction) { try { if (!req.user) return next(createError('Authentication required.', 401)); res.status(201).json({ success: true, data: await GovernanceService.createAnnualClosing(Number(req.body.year), req.body.notes, req.user) }); } catch (error) { next(error); } }
  static async annualAction(req: AuthRequest, res: Response, next: NextFunction) { try { if (!req.user) return next(createError('Authentication required.', 401)); const action = req.params.action as 'review' | 'approve' | 'lock'; if (!['review', 'approve', 'lock'].includes(action)) return next(createError('Invalid annual-closing action.', 400)); res.json({ success: true, data: await GovernanceService.transitionAnnualClosing(req.params.id, action, req.user) }); } catch (error) { next(error); } }
  static async annualList(_req: AuthRequest, res: Response, next: NextFunction) { try { res.json({ success: true, data: await GovernanceService.listAnnualClosings() }); } catch (error) { next(error); } }
  static async policyList(_req: AuthRequest, res: Response, next: NextFunction) { try { res.json({ success: true, data: await GovernanceService.listPolicies() }); } catch (error) { next(error); } }
  static async policyCreate(req: AuthRequest, res: Response, next: NextFunction) { try { if (!req.user) return next(createError('Authentication required.', 401)); const { serialNumber, title, category, content } = req.body; if (!serialNumber || !title || !category || !content) return next(createError('serialNumber, title, category, and content are required.', 400)); res.status(201).json({ success: true, data: await GovernanceService.createPolicy({ serialNumber: Number(serialNumber), title, category, content }, req.user) }); } catch (error) { next(error); } }
  static async policyAmend(req: AuthRequest, res: Response, next: NextFunction) { try { if (!req.user) return next(createError('Authentication required.', 401)); res.json({ success: true, data: await GovernanceService.amendPolicy(req.params.id, req.body, req.user) }); } catch (error) { next(error); } }
  static async policyVersions(req: AuthRequest, res: Response, next: NextFunction) { try { res.json({ success: true, data: await GovernanceService.policyVersions(req.params.id) }); } catch (error) { next(error); } }
  static async exitList(_req: AuthRequest, res: Response, next: NextFunction) { try { res.json({ success: true, data: await GovernanceService.listExits() }); } catch (error) { next(error); } }
  static async exitPropose(req: AuthRequest, res: Response, next: NextFunction) { try { if (!req.user) return next(createError('Authentication required.', 401)); res.status(201).json({ success: true, data: await GovernanceService.proposeExit(req.body.memberId, Number(req.body.eligibleAmount), req.body.notes, req.user) }); } catch (error) { next(error); } }
  static async exitApprove(req: AuthRequest, res: Response, next: NextFunction) { try { if (!req.user) return next(createError('Authentication required.', 401)); res.json({ success: true, data: await GovernanceService.approveExit(req.params.id, req.user) }); } catch (error) { next(error); } }
  static async exitPay(req: AuthRequest, res: Response, next: NextFunction) { try { if (!req.user) return next(createError('Authentication required.', 401)); res.json({ success: true, data: await GovernanceService.payExitInstallment(req.params.id, Number(req.body.index), req.body.custodyAccountId, req.user) }); } catch (error) { next(error); } }
}
