import React, { useCallback, useEffect, useState } from 'react';
import { Eye, X } from 'lucide-react';
import { apiRequest } from '../services/api';
import { usePreferences } from '../context/PreferencesContext';

type Detail = { month: string; shareCount: number; principalDue: number; penaltyDue: number; penaltyWaived: number };
type DueRow = { _id: string; member: { _id: string; memberId: string; name: string; phone: string }; principalDue: number; penaltyDue: number; cashoutDue: number; totalDue: number; details: Detail[] };
type Dues = { availableYears: number[]; summary: { total: number; principal: number; penalty: number; cashout: number; currentPrincipal: number; previousPrincipal: number }; filters: { referencePeriod: string; previousPeriod: string }; rows: DueRow[] };
const money = (value: number) => `৳${Number(value || 0).toLocaleString('en-BD', { minimumFractionDigits: 2 })}`;

export const DuesPage: React.FC = () => {
  const { t } = usePreferences(); const [data, setData] = useState<Dues | null>(null); const [year, setYear] = useState('ALL'); const [month, setMonth] = useState('ALL'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<DueRow | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams(); if (year !== 'ALL') params.set('year', year); if (month !== 'ALL') params.set('month', month); if (search.trim()) params.set('search', search.trim()); const response = await apiRequest<Dues>(`/payments/dues?${params}`); setData(response.data); } finally { setLoading(false); } }, [year, month, search]);
  useEffect(() => { void load(); }, [load]);
  return <div className="space-y-6 max-w-7xl mx-auto pb-10"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-300">{t('Payment overview')}</p><h1 className="text-2xl sm:text-3xl font-extrabold text-white mt-1">{t('Outstanding Dues')}</h1><p className="text-sm text-gray-400 mt-1">{t('Review each member’s unpaid monthly share, penalty, and any cash-out charge recorded by the accountant.')}</p></div>
    <div className="glass-card p-4 flex flex-col lg:flex-row gap-3"><input className="form-input flex-1" value={search} onChange={(e) => setSearch(e.target.value)} placeholder={t('Search member ID, name, or phone...')} /><select className="form-select lg:w-36" value={year} onChange={(e) => setYear(e.target.value)}><option value="ALL">{t('All years')}</option>{(data?.availableYears || []).map((item) => <option key={item}>{item}</option>)}</select><select className="form-select lg:w-40" value={month} onChange={(e) => setMonth(e.target.value)}><option value="ALL">{t('All months')}</option>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{t(new Date(2024, index, 1).toLocaleString('en', { month: 'long' }))}</option>)}</select></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{[[t('Total Due'),data?.summary.total,'text-rose-300'],[t('Principal due'),data?.summary.principal,'text-blue-300'],[t('Penalty due'),data?.summary.penalty,'text-amber-300'],[t('Cash-out due'),data?.summary.cashout,'text-fuchsia-300']].map(([label,value,color]) => <div key={String(label)} className="glass-card p-4"><p className="text-xs font-bold text-gray-400 uppercase">{label}</p><p className={`mt-2 text-2xl font-extrabold ${color}`}>{money(Number(value))}</p></div>)}</div>
    <div className="table-container glass-card overflow-x-auto"><table className="data-table min-w-[780px]"><thead><tr><th>{t('Member')}</th><th>{t('Months due')}</th><th>{t('Principal due')}</th><th>{t('Penalty due')}</th><th>{t('Cash-out due')}</th><th>{t('Total Due')}</th><th>{t('Details')}</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="text-center py-10 text-gray-400">{t('Loading outstanding dues...')}</td></tr> : !data?.rows.length ? <tr><td colSpan={7} className="text-center py-10 text-gray-400">{t('No outstanding dues match the selected filters.')}</td></tr> : data.rows.map((row) => <tr key={row._id}><td><strong>{row.member.name}</strong><span className="block text-xs text-gray-400">{row.member.memberId}</span></td><td>{row.details.length ? row.details.length : '—'}</td><td>{money(row.principalDue)}</td><td>{money(row.penaltyDue)}</td><td>{money(row.cashoutDue)}</td><td className="font-bold text-rose-200">{money(row.totalDue)}</td><td><button className="btn btn-secondary btn-sm" onClick={() => setSelected(row)}><Eye size={15}/>{t('View')}</button></td></tr>)}</tbody></table></div>
    {selected && <div className="modal-overlay"><div className="modal-content max-w-2xl"><div className="p-5 border-b border-white/10 flex justify-between"><div><h2 className="font-bold text-white">{selected.member.name}</h2><p className="text-sm text-gray-400">{selected.member.memberId} · {t('Dues details')}</p></div><button onClick={() => setSelected(null)} className="text-gray-400"><X /></button></div><div className="p-5 space-y-4"><p className="text-sm text-gray-300">{t('The following months remain unpaid. Any approved penalty waiver is shown separately.')}</p><div className="table-container"><table className="data-table"><thead><tr><th>{t('Month')}</th><th>{t('Principal due')}</th><th>{t('Penalty due')}</th><th>{t('Penalty waiver')}</th></tr></thead><tbody>{selected.details.map((item) => <tr key={item.month}><td>{item.month}</td><td>{money(item.principalDue)}</td><td>{money(item.penaltyDue)}</td><td>{money(item.penaltyWaived)}</td></tr>)}</tbody></table></div>{selected.cashoutDue > 0 && <p className="rounded-lg border border-fuchsia-400/20 bg-fuchsia-400/5 p-3 text-sm text-fuchsia-100">{t('Separately recorded cash-out charge due:')} {money(selected.cashoutDue)}</p>}<div className="flex justify-end"><button className="btn btn-secondary" onClick={() => setSelected(null)}>{t('Close')}</button></div></div></div></div>}
  </div>;
};
