import React, { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiRequest } from '../services/api';

export const PasswordResetPage: React.FC = () => {
  const [params] = useSearchParams(); const [email, setEmail] = useState(''); const [token, setToken] = useState(params.get('token') || ''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const request = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const response = await apiRequest<{ developmentResetToken?: string }>('/auth/forgot-password', { method: 'POST', body: JSON.stringify({ email }) }); setMessage(response.data?.developmentResetToken ? `Development reset token: ${response.data.developmentResetToken}` : response.message || 'Recovery instructions issued.'); if (response.data?.developmentResetToken) setToken(response.data.developmentResetToken); } catch (e) { setError((e as Error).message); } };
  const reset = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const response = await apiRequest('/auth/reset-password', { method: 'POST', body: JSON.stringify({ token, password }) }); setMessage(response.message || 'Password reset successful.'); } catch (e) { setError((e as Error).message); } };
  return <div className="min-h-screen flex items-center justify-center p-4 bg-[#0B0F19]"><div className="glass-card w-full max-w-md p-6 space-y-5"><h1 className="text-2xl font-bold text-white">Password recovery</h1><p className="text-sm text-gray-400">Reset links are single-use and expire after 15 minutes.</p>{error && <div className="alert alert-error">{error}</div>}{message && <div className="alert alert-success break-all">{message}</div>}<form onSubmit={request} className="space-y-3"><input className="form-input" required type="email" placeholder="Account email" value={email} onChange={(e) => setEmail(e.target.value)} /><button className="btn btn-secondary w-full">Request reset</button></form><form onSubmit={reset} className="space-y-3 border-t border-white/10 pt-4"><input className="form-input" required placeholder="Reset token" value={token} onChange={(e) => setToken(e.target.value)} /><input className="form-input" required minLength={10} type="password" placeholder="New password (10+ characters)" value={password} onChange={(e) => setPassword(e.target.value)} /><button className="btn btn-primary w-full">Set new password</button></form><Link className="text-sm text-blue-300" to="/login">Back to sign in</Link></div></div>;
};
