import React from 'react';
import { CheckCircle2, Languages, Monitor, Moon, Settings2, Sun } from 'lucide-react';
import { usePreferences } from '../context/PreferencesContext';

export const PreferencesPage: React.FC = () => {
  const { language, setLanguage, theme, setTheme, t } = usePreferences();
  const deviceLanguage = typeof navigator === 'undefined' ? 'en' : navigator.language;

  return <div className="space-y-6 sm:space-y-8 max-w-3xl mx-auto pb-10">
    <header><div className="flex items-center gap-2 text-blue-400"><Settings2 size={18} /><span className="text-xs font-bold uppercase tracking-wider">{t('Personal Settings')}</span></div><h1 className="mt-1 text-2xl sm:text-3xl font-extrabold text-white">{t('Language & Appearance')}</h1><p className="mt-1 text-sm text-gray-400">{t('Choose how NS Foundation is displayed on this device.')}</p></header>

    <section className="glass-card p-5 sm:p-6"><div className="flex items-start gap-3"><div className="rounded-xl bg-blue-500/10 border border-blue-500/20 p-2.5 text-blue-300"><Languages size={20} /></div><div><h2 className="font-bold text-white">{t('Language')}</h2><p className="text-sm text-gray-400 mt-1">{t('Your choice is saved for this browser. The first visit follows your device language when available.')}</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-5"><button onClick={() => setLanguage('en')} className={`rounded-xl border p-4 text-left transition-colors ${language === 'en' ? 'border-blue-400 bg-blue-500/10' : 'border-white/10 bg-slate-900/60 hover:border-white/25'}`}><div className="flex items-center justify-between"><span className="font-bold text-white">English</span>{language === 'en' && <CheckCircle2 size={18} className="text-blue-300" />}</div><p className="text-xs text-gray-400 mt-1">English (Bangladesh)</p></button><button onClick={() => setLanguage('bn')} className={`rounded-xl border p-4 text-left transition-colors ${language === 'bn' ? 'border-blue-400 bg-blue-500/10' : 'border-white/10 bg-slate-900/60 hover:border-white/25'}`}><div className="flex items-center justify-between"><span className="font-bold text-white">বাংলা</span>{language === 'bn' && <CheckCircle2 size={18} className="text-blue-300" />}</div><p className="text-xs text-gray-400 mt-1">বাংলা (বাংলাদেশ)</p></button></div><p className="mt-4 flex items-center gap-2 text-xs text-gray-500"><Monitor size={14} />{t('Device language')}: {deviceLanguage}</p></section>

    <section className="glass-card p-5 sm:p-6"><div className="flex items-start gap-3"><div className="rounded-xl bg-violet-500/10 border border-violet-500/20 p-2.5 text-violet-300">{theme === 'dark' ? <Moon size={20} /> : <Sun size={20} />}</div><div><h2 className="font-bold text-white">{t('Appearance')}</h2><p className="text-sm text-gray-400 mt-1">{t('Choose the colour theme that is most comfortable for you.')}</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-5"><button onClick={() => setTheme('dark')} className={`rounded-xl border p-4 text-left ${theme === 'dark' ? 'border-violet-400 bg-violet-500/10' : 'border-white/10 bg-slate-900/60'}`}><Moon size={18} className="text-violet-300 mb-2" /><span className="font-semibold text-white">{t('Dark theme')}</span></button><button onClick={() => setTheme('light')} className={`rounded-xl border p-4 text-left ${theme === 'light' ? 'border-violet-400 bg-violet-500/10' : 'border-white/10 bg-slate-900/60'}`}><Sun size={18} className="text-amber-300 mb-2" /><span className="font-semibold text-white">{t('Light theme')}</span></button></div></section>
  </div>;
};
