import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { apiRequest } from '../services/api';

export const RegisterPage: React.FC = () => {
  const [form, setForm] = useState({ name: '', email: '', phone: '', password: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const navigate = useNavigate();
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const response = await apiRequest('/auth/public-register', { method: 'POST', body: JSON.stringify(form) }); setMessage(response.message || 'Registration successful.'); setTimeout(() => navigate('/login'), 900); } catch (e) { setError((e as Error).message); } };
  return <div className="min-h-screen flex items-center justify-center p-4 bg-[#0B0F19]"><form onSubmit={submit} className="glass-card w-full max-w-md p-6 space-y-4"><h1 className="text-2xl font-bold text-white">Create account</h1><p className="text-sm text-gray-400">Public registration creates a Member account only. Administrators grant staff permissions.</p>{error && <div className="alert alert-error">{error}</div>}{message && <div className="alert alert-success">{message}</div>}<input className="form-input" required placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className="form-input" required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input className="form-input" placeholder="International phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input className="form-input" required minLength={10} type="password" placeholder="Password (10+ characters)" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button className="btn btn-primary w-full">Register</button><Link className="text-sm text-blue-300 hover:text-blue-200" to="/login">Back to sign in</Link></form></div>;
};
